import React, { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import caseApi from '../../api/caseApi.js'
import documentApi from '../../api/documentApi.js'
import hearingApi from '../../api/hearingApi.js'
import messageApi from '../../api/messageApi.js'
import aiApi from '../../api/aiApi.js'
import { useAuth } from '../../contexts/AuthContext.jsx'
import { motion } from 'framer-motion'
import {
  ArrowBack, CheckCircle, Send, Gavel, CalendarMonth
} from '@mui/icons-material'
import toast from 'react-hot-toast'

const TABS = ['Overview', 'Timeline', 'Documents', 'Hearings', 'Messages']

export default function CaseWorkspace() {
  const { id } = useParams()
  const { user } = useAuth()
  const navigate = useNavigate()
  
  const [activeTab, setActiveTab] = useState('Overview')
  const [caseData, setCaseData] = useState(null)
  const [documents, setDocuments] = useState([])
  const [hearings, setHearings] = useState([])
  const [messages, setMessages] = useState([])
  const [newMessage, setNewMessage] = useState('')
  const [loading, setLoading] = useState(true)

  // Scheduling state for Judge
  const [showScheduleForm, setShowScheduleForm] = useState(false)
  const [hearingDate, setHearingDate] = useState('')
  const [hearingLocation, setHearingLocation] = useState('')
  const [hearingRemarks, setHearingRemarks] = useState('')

  // AI features
  const [riskAnalysis, setRiskAnalysis] = useState(null)
  const [isAnalyzingRisk, setIsAnalyzingRisk] = useState(false)
  const [summarizingDocId, setSummarizingDocId] = useState(null)
  const [docSummaries, setDocSummaries] = useState({})

  const runRiskAnalysis = async () => {
    setIsAnalyzingRisk(true)
    try {
      const docNames = documents.map(d => d.fileName)
      const res = await aiApi.analyzeRisk(caseData.description, docNames)
      setRiskAnalysis(res.data)
      toast.success('Risk analysis complete')
    } catch (err) {
      toast.error('AI risk analysis failed')
    } finally {
      setIsAnalyzingRisk(false)
    }
  }

  const handleSummarizeDoc = async (docId, fileName) => {
    setSummarizingDocId(docId)
    try {
      const res = await aiApi.summarizeDocument(`Simulate summary for ${fileName}`)
      setDocSummaries(prev => ({ ...prev, [docId]: res.data.summary || 'Summary generated by AI.' }))
      toast.success('Document summarized')
    } catch (err) {
      toast.error('Failed to summarize document')
    } finally {
      setSummarizingDocId(null)
    }
  }

  const fetchWorkspaceData = async () => {
    try {
      const [caseRes, docsRes, hearingsRes, messagesRes] = await Promise.all([
        caseApi.getCaseById(id),
        documentApi.getDocumentsByCase(id),
        hearingApi.getHearingsByCase(id),
        messageApi.getMessagesByCase(id)
      ])
      setCaseData(caseRes.data)
      setDocuments(docsRes.data)
      setHearings(hearingsRes.data)
      setMessages(messagesRes.data)
    } catch (err) {
      console.error('Failed to load workspace:', err)
      toast.error('Failed to load case details')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchWorkspaceData()
    // Poll for new messages every 4 seconds when in the messages tab
    let interval
    if (activeTab === 'Messages') {
      interval = setInterval(() => {
        messageApi.getMessagesByCase(id).then(res => setMessages(res.data))
      }, 4000)
    }
    return () => clearInterval(interval)
  }, [id, activeTab])

  const getReceiverId = () => {
    if (!caseData) return null
    if (user.role === 'CITIZEN' || user.role === 'citizen') {
      return caseData.petitionerLawyerId || caseData.respondentLawyerId || caseData.respondentId || 3
    }
    // Lawyer chats with the petitioner
    return caseData.petitionerId
  }

  const handleSendMessage = async () => {
    if (!newMessage.trim()) return
    const receiverId = getReceiverId()
    if (!receiverId) {
      toast.error('No messaging participant found')
      return
    }
    try {
      await messageApi.sendMessage(receiverId, newMessage, caseData.id)
      setNewMessage('')
      // Instantly reload messages
      const res = await messageApi.getMessagesByCase(id)
      setMessages(res.data)
    } catch (err) {
      toast.error('Failed to send message')
    }
  }

  const handleFileUpload = async (e) => {
    const file = e.target.files[0]
    if (!file) return
    try {
      await documentApi.uploadDocument(caseData.id, file, 'EVIDENCE')
      toast.success('Document uploaded successfully!')
      const docsRes = await documentApi.getDocumentsByCase(id)
      setDocuments(docsRes.data)
    } catch (err) {
      toast.error('Failed to upload document')
    }
  }

  const handleScheduleHearing = async (e) => {
    e.preventDefault()
    if (!hearingDate || !hearingLocation) {
      toast.error('Please enter hearing date and location.')
      return
    }
    try {
      await hearingApi.scheduleHearing({
        caseId: caseData.id,
        hearingDate: new Date(hearingDate).toISOString().slice(0, 19),
        location: hearingLocation,
        remarks: hearingRemarks
      })
      toast.success('Hearing scheduled successfully!')
      setShowScheduleForm(false)
      setHearingDate('')
      setHearingLocation('')
      setHearingRemarks('')
      // Reload
      fetchWorkspaceData()
    } catch (err) {
      toast.error('Failed to schedule hearing')
    }
  }

  const handleUpdateStatus = async (status) => {
    try {
      await caseApi.updateCaseStatus(caseData.id, status)
      toast.success(`Case status updated to ${status.toLowerCase()}`)
      fetchWorkspaceData()
    } catch (err) {
      toast.error('Failed to update case status')
    }
  }

  if (loading) {
    return (
      <div className="loading-overlay" style={{ background: 'transparent' }}>
        <div className="spinner" style={{ width: 40, height: 40 }}></div>
      </div>
    )
  }

  if (!caseData) {
    return (
      <div className="empty-state" style={{ marginTop: 100 }}>
        <div className="empty-state-icon">🔍</div>
        <div className="empty-state-title">Case not found</div>
        <button className="btn btn-primary" onClick={() => navigate('/cases')}>Back to Cases</button>
      </div>
    )
  }

  const getStatusBadge = (status) => {
    const map = { filed: 'badge-info', under_verification: 'badge-warning', under_review: 'badge-primary', hearing_scheduled: 'badge-info', evidence_review: 'badge-warning', judgment_reserved: 'badge-gold', closed: 'badge-success', dismissed: 'badge-danger' }
    const labels = { filed: 'Filed', under_verification: 'Under Verification', under_review: 'Under Review', hearing_scheduled: 'Hearing Scheduled', evidence_review: 'Evidence Review', judgment_reserved: 'Judgment Reserved', closed: 'Closed', dismissed: 'Dismissed' }
    return <span className={`badge ${map[status] || 'badge-neutral'}`}>{labels[status] || status}</span>
  }

  const getVerifBadge = (s) => {
    if (s === 'verified' || s === 'VERIFIED') return <span className="badge badge-success">✓ Verified</span>
    if (s === 'rejected' || s === 'REJECTED') return <span className="badge badge-danger">✕ Rejected</span>
    return <span className="badge badge-warning">⏳ Pending</span>
  }

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <button className="btn btn-ghost btn-sm" onClick={() => navigate('/cases')} style={{ marginBottom: 12 }}>
          <ArrowBack style={{ fontSize: 16 }} /> Back to Cases
        </button>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 4 }}>
              <h1 className="page-title" style={{ fontSize: '1.5rem' }}>{caseData.title}</h1>
              {getStatusBadge(caseData.status)}
            </div>
            <p style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: '0.85rem', color: '#4a4fff', fontWeight: 600 }}>
              {caseData.caseNumber}
            </p>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="tabs">
        {TABS.map(tab => (
          <button key={tab} className={`tab ${activeTab === tab ? 'active' : ''}`} onClick={() => setActiveTab(tab)}>
            {tab}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      {activeTab === 'Overview' && (
        <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 24 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
            {/* Case Info */}
            <div className="card">
              <div className="card-header"><h3 className="card-title">Case Information</h3></div>
              <div className="card-body">
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
                  {[
                    { label: 'Case Type', value: caseData.category, icon: '📋' },
                    { label: 'Court', value: caseData.courtName || 'Not assigned', icon: '🏛️' },
                    { label: 'Filed On', value: caseData.filingDate, icon: '📅' },
                    { label: 'Priority', value: caseData.priority, icon: '🔴' },
                    { label: 'Judge', value: caseData.judgeName || 'Not assigned', icon: '⚖️' },
                    { label: 'Documents', value: `${documents.length} files`, icon: '📄' },
                  ].map((item, i) => (
                    <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                      <span style={{ fontSize: '1.2rem' }}>{item.icon}</span>
                      <div>
                        <div style={{ fontSize: '0.72rem', color: '#94a3b8', fontWeight: 600, textTransform: 'uppercase' }}>{item.label}</div>
                        <div style={{ fontWeight: 600, fontSize: '0.9rem', textTransform: 'capitalize' }}>{item.value}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Description */}
            <div className="card">
              <div className="card-header"><h3 className="card-title">Case Description</h3></div>
              <div className="card-body">
                <p style={{ fontSize: '0.9rem', color: '#334155', lineHeight: 1.7 }}>{caseData.description}</p>
              </div>
            </div>

            {/* Judge Actions */}
            {(user.role === 'JUDGE' || user.role === 'judge') && (
              <div className="card">
                <div className="card-header"><h3 className="card-title">Update Case Status</h3></div>
                <div className="card-body" style={{ display: 'flex', gap: 12 }}>
                  <button className="btn btn-primary" onClick={() => handleUpdateStatus('under_review')}>Under Review</button>
                  <button className="btn btn-warning" onClick={() => handleUpdateStatus('evidence_review')}>Evidence Review</button>
                  <button className="btn btn-success" onClick={() => handleUpdateStatus('closed')}>Close Case</button>
                </div>
              </div>
            )}
          </div>

          {/* Participants */}
          <div className="card">
            <div className="card-header"><h3 className="card-title">Participants</h3></div>
            <div className="card-body" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {[
                { role: 'Petitioner', name: caseData.petitionerName, color: '#3b82f6' },
                { role: 'Respondent', name: caseData.respondentName, color: '#f43f5e' },
                { role: 'Petitioner Lawyer', name: caseData.petitionerLawyerName || 'Not assigned', color: '#8b5cf6' },
                { role: 'Respondent Lawyer', name: caseData.respondentLawyerName || 'Not assigned', color: '#f59e0b' },
                { role: 'Judge', name: caseData.judgeName || 'Not assigned', color: '#059669' },
              ].map((p, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div className="avatar" style={{ background: p.color, width: 36, height: 36, fontSize: '0.75rem' }}>
                    {p.name?.split(' ').map(n => n[0]).join('').substring(0, 2) || '?'}
                  </div>
                  <div>
                    <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{p.name}</div>
                    <div style={{ fontSize: '0.72rem', color: '#94a3b8' }}>{p.role}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* AI Risk Analysis */}
          <div className="card">
            <div className="card-header"><h3 className="card-title">✨ AI Risk Analysis</h3></div>
            <div className="card-body">
              {!riskAnalysis && !isAnalyzingRisk && (
                <div style={{ textAlign: 'center', padding: '20px 0' }}>
                  <button className="btn btn-outline" onClick={runRiskAnalysis}>Run AI Risk Analysis</button>
                </div>
              )}
              {isAnalyzingRisk && (
                <div style={{ textAlign: 'center', padding: '20px 0' }}>
                  <span className="spinner" style={{ width: 24, height: 24 }}></span>
                </div>
              )}
              {riskAnalysis && (
                <div>
                  <div style={{ marginBottom: 12 }}>
                    <strong>Readiness Score:</strong> <span style={{ color: riskAnalysis.score > 70 ? '#10b981' : '#f59e0b', fontWeight: 'bold' }}>{riskAnalysis.score}%</span>
                  </div>
                  {riskAnalysis.missingDocuments && riskAnalysis.missingDocuments.length > 0 && (
                    <div style={{ marginBottom: 12 }}>
                      <strong>Missing Documents:</strong>
                      <ul style={{ marginLeft: 20, marginTop: 4, fontSize: '0.9rem' }}>
                        {riskAnalysis.missingDocuments.map((doc, i) => <li key={i}>{doc}</li>)}
                      </ul>
                    </div>
                  )}
                  {riskAnalysis.analysis && (
                    <div style={{ fontSize: '0.9rem', color: '#334155', background: '#f8fafc', padding: 12, borderRadius: 8 }}>
                      <strong>Analysis:</strong>
                      <p style={{ marginTop: 4 }}>{riskAnalysis.analysis}</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {activeTab === 'Timeline' && (
        <div className="card">
          <div className="card-body" style={{ padding: 32 }}>
            <div className="timeline">
              {caseData.timeline && caseData.timeline.length > 0 ? (
                caseData.timeline.map((item, i) => (
                  <div key={i} className={`timeline-item ${item.status}`}>
                    <div className="timeline-dot">
                      {item.status === 'completed' && <CheckCircle style={{ fontSize: 12, color: 'white', position: 'absolute', top: 0, left: 0 }} />}
                    </div>
                    <div className="timeline-title">{item.step}</div>
                    <div className="timeline-date">{item.date || 'Pending'}</div>
                    {item.description && <div className="timeline-desc">{item.description}</div>}
                  </div>
                ))
              ) : (
                <div style={{ textAlign: 'center', color: '#94a3b8' }}>Timeline not generated.</div>
              )}
            </div>
          </div>
        </div>
      )}

      {activeTab === 'Documents' && (
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Case Documents ({documents.length})</h3>
            {(user.role === 'citizen' || user.role === 'lawyer' || user.role === 'CITIZEN' || user.role === 'LAWYER') && (
              <label className="btn btn-primary btn-sm" style={{ cursor: 'pointer' }}>
                Upload Document
                <input type="file" style={{ display: 'none' }} onChange={handleFileUpload} />
              </label>
            )}
          </div>
          <div style={{ padding: 0 }}>
            {documents.length === 0 ? (
              <div className="empty-state">
                <div className="empty-state-icon">📂</div>
                <div className="empty-state-title">No documents uploaded yet</div>
              </div>
            ) : (
              <table className="data-table">
                <thead>
                  <tr><th>File</th><th>Category</th><th>Uploaded At</th><th>Status</th><th>Actions</th></tr>
                </thead>
                <tbody>
                  {documents.map(doc => (
                    <React.Fragment key={doc.id}>
                    <tr>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                          <span style={{ fontSize: '1.2rem' }}>{doc.fileType === 'pdf' ? '📄' : '🖼️'}</span>
                          <div>
                            <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{doc.fileName}</div>
                            <div style={{ fontSize: '0.72rem', color: '#94a3b8' }}>{doc.fileSize || 'N/A'}</div>
                          </div>
                        </div>
                      </td>
                      <td><span className="badge badge-neutral">{doc.category || 'Evidence'}</span></td>
                      <td style={{ fontSize: '0.82rem', color: '#94a3b8' }}>
                        {doc.uploadedAt ? new Date(doc.uploadedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'N/A'}
                      </td>
                      <td>{getVerifBadge(doc.verificationStatus)}</td>
                      <td>
                        <button 
                          className="btn btn-ghost btn-sm" 
                          onClick={() => handleSummarizeDoc(doc.id, doc.fileName)}
                          disabled={summarizingDocId === doc.id}
                          style={{ color: '#8b5cf6' }}
                        >
                          {summarizingDocId === doc.id ? '...' : '✨ Summarize'}
                        </button>
                      </td>
                    </tr>
                    {docSummaries[doc.id] && (
                      <tr key={`summary-${doc.id}`}>
                        <td colSpan={5} style={{ padding: '12px 24px', background: '#f8fafc' }}>
                          <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                            <span style={{ fontSize: '1.2rem' }}>✨</span>
                            <div>
                              <div style={{ fontWeight: 600, fontSize: '0.85rem', color: '#8b5cf6', marginBottom: 4 }}>AI Summary</div>
                              <div style={{ fontSize: '0.9rem', color: '#334155', lineHeight: 1.6 }}>{docSummaries[doc.id]}</div>
                            </div>
                          </div>
                        </td>
                      </tr>
                    )}
                    </React.Fragment>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      )}

      {activeTab === 'Hearings' && (
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Hearing History</h3>
            {(user.role === 'judge' || user.role === 'JUDGE') && (
              <button className="btn btn-primary btn-sm" onClick={() => setShowScheduleForm(true)}>Schedule Hearing</button>
            )}
          </div>
          <div className="card-body" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {showScheduleForm && (
              <form onSubmit={handleScheduleHearing} style={{ padding: 20, border: '1px solid #e2e8f0', borderRadius: 12, display: 'flex', flexDirection: 'column', gap: 12 }}>
                <h4>Schedule Hearing</h4>
                <div className="form-group">
                  <label className="form-label">Date and Time</label>
                  <input type="datetime-local" className="form-input" value={hearingDate} onChange={e => setHearingDate(e.target.value)} required />
                </div>
                <div className="form-group">
                  <label className="form-label">Location</label>
                  <input className="form-input" placeholder="e.g. Room 3, City Civil Court" value={hearingLocation} onChange={e => setHearingLocation(e.target.value)} required />
                </div>
                <div className="form-group">
                  <label className="form-label">Remarks</label>
                  <textarea className="form-input form-textarea" placeholder="Remarks..." value={hearingRemarks} onChange={e => setHearingRemarks(e.target.value)} />
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button className="btn btn-primary" type="submit">Schedule</button>
                  <button className="btn btn-outline" type="button" onClick={() => setShowScheduleForm(false)}>Cancel</button>
                </div>
              </form>
            )}

            {hearings.length === 0 ? (
              <div className="empty-state">
                <div className="empty-state-icon">📅</div>
                <div className="empty-state-title">No hearings scheduled</div>
              </div>
            ) : (
              hearings.map(h => (
                <div key={h.id} style={{
                  padding: 20, borderRadius: 12, border: '1px solid #e2e8f0',
                  background: h.status === 'scheduled' || h.status === 'SCHEDULED' ? '#f0f9ff' : 'white'
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
                    <div>
                      <span className={`badge ${h.status === 'scheduled' || h.status === 'SCHEDULED' ? 'badge-info' : 'badge-success'}`}>
                        {h.status === 'scheduled' || h.status === 'SCHEDULED' ? '📅 Upcoming' : '✓ Completed'}
                      </span>
                    </div>
                    <div style={{ fontWeight: 600 }}>
                      {new Date(h.hearingDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
                      {' at '}
                      {new Date(h.hearingDate).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
                    </div>
                  </div>
                  <div style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: 8 }}>📍 {h.location}</div>
                  {h.remarks && (
                    <div style={{ fontSize: '0.9rem', color: '#334155', padding: 12, background: '#f8fafc', borderRadius: 8 }}>
                      <strong>Remarks:</strong> {h.remarks}
                    </div>
                  )}
                  {h.orders && (
                    <div style={{ fontSize: '0.9rem', color: '#334155', padding: 12, background: '#fef3c7', borderRadius: 8, marginTop: 8 }}>
                      <strong>📜 Court Order:</strong> {h.orders}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>
      )}

      {activeTab === 'Messages' && (
        <div className="card" style={{ height: 500, display: 'flex', flexDirection: 'column' }}>
          <div className="card-header"><h3 className="card-title">Case Discussion</h3></div>
          <div style={{ flex: 1, padding: 24, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 12 }}>
            {messages.length === 0 ? (
              <div style={{ textAlign: 'center', color: '#94a3b8', padding: '32px 0' }}>
                No messages yet. Send a message below to start case discussion.
              </div>
            ) : (
              messages.map(msg => (
                <div key={msg.id} className={`chat-message ${msg.senderId === user.id ? 'sent' : 'received'}`}>
                  <div className="avatar" style={{ background: msg.senderId === user.id ? '#4a4fff' : '#64748b', width: 32, height: 32, fontSize: '0.7rem' }}>
                    {msg.senderName ? msg.senderName.split(' ').map(n => n[0]).join('').substring(0, 2) : '?'}
                  </div>
                  <div>
                    <div style={{ fontSize: '0.72rem', color: '#94a3b8', marginBottom: 4 }}>{msg.senderName}</div>
                    <div className="chat-bubble">{msg.content}</div>
                    <div className="chat-time">
                      {msg.sentAt ? new Date(msg.sentAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : ''}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
          <div className="chat-input-bar">
            <input className="chat-input" placeholder="Type a message..." value={newMessage} onChange={e => setNewMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSendMessage()} />
            <button className="btn btn-primary btn-icon" onClick={handleSendMessage}><Send style={{ fontSize: 18 }} /></button>
          </div>
        </div>
      )}
    </div>
  )
}
